### PR TITLE
Implement nonzero return code on incomplete coverage

### PR DESCRIPTION
**Pull request by arrdem**
Abuse a temporary file to pass back a numeric return code. This allows the calling JVM to exit with a return code computed by the child, in which the `eval-in-project` took place. This change could probably be generalized to allow `eval-in-project` to return arbitrary EDN encoded data, but that's for another day.

### CODE REVIEW

**Comment by technomancy** [comment]
I would rather get rid of the `leiningen.radagast` namespace entirely and just invoke a `-main` function using `lein run -m radagast.coverage`. However, the current plugin reads `:radagast/ns-whitelist` from the project map. Maybe there's a better way this could be configured?

**Comment by arrdem** [comment]
In most cases, the `:radagast/ns-whitelist` regex is only going to be a pattern matching the root namespace under which all the other project code sits. It may be possible to use the same source file discovery lib of Raynes that lein depends on to try and compute the ns-whitelist pattern automatically but that's relatively fragile. `argv` is always an option, abet a poor one as it confuses the current `argv` list of namespaces with the var pattern. Making the var pattern the first element by convention would work tho.

**Comment by technomancy** [comment]
Random idea for a change inside Leiningen itself:

http://p.hagelb.org/project-splice-into-args.diff.html

This would allow you to configure `:aliases {"radagast" ["run" "-m" "radagast.coverage" :project/radagast-whitelist]}` and move the `eval-in-project` form to `-main` inside the proper namespace.

**Comment by arrdem** [comment]
:thumbsup: You'd still ned radagast as a dev dependency to be able to do this, but I think this solves the issue of radagast really being in-project code injection and not part of lein nicely while maintaining radagast as a lein command.

**Comment by technomancy** [comment]
Cool. Can you update this to use a `-main` function that calls `System/exit`? I've made the change above in Leiningen's master branch.

**Comment by technomancy** [comment]
Looks good. But maybe in order to provide maximum reusability from the repl, it could be reorganized so `-main` handles _only_ the CLI-specific things like reading the whitelist into a regex and exiting. Seems like the rest could be invokeable from a repl.

**Comment by arrdem** [comment]
Man how do people watch TV, this stuff's like 25% wasted time. Fixing that. Patch incomming.

**Comment by technomancy** [comment]
Had to push some fixes to this, but I've merged it to master. If you want to give the latest a try, I will cut a 2.0.0 release next.

**Pull request merged**
