### PR TITLE
Fix README listed version

### PR DESCRIPTION
**Pull request by arrdem**
Because 1.1.1 isn't updated for lein 2.0.0 and dies, this being a source of user confusion.

### CODE REVIEW

**Comment by technomancy** [comment]
We don't have `:dev-dependencies` any more; this should point people to the `:user` profile, or the `:dev` profile if it's going to be part of the standard workflow for a project.

**Comment by arrdem** [comment]
Agreed, I've modified my personal `~/.lein/profiles.clj` to add radagast as a standard injected dependency as my clean tests and total tests pre-commit hooks are eventually going to make it to all my projects. As this sort of testing dicipline is the exception rather than the rule I feel simply demonstrating how to add radagast to the dev profile should be sufficient.

**Comment by arrdem** [comment]
Tweaked the README to show a `:dev` profile with the appropriate `:dependencies`.

**Comment by technomancy** [comment]
Looks good; thanks.

**Pull request merged**
